apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcosidekick
  namespace: aegismesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcosidekick
  template:
    metadata:
      labels:
        app: falcosidekick
    spec:
      automountServiceAccountToken: false
      containers:
      - name: falcosidekick
        image: falcosecurity/falcosidekick:2.28.0
        ports:
        - containerPort: 2801
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
            ephemeral-storage: 128Mi
          limits:
            cpu: 200m
            memory: 128Mi
            ephemeral-storage: 256Mi
        env:
        - name: WEBHOOK_ADDRESS
          value: "http://security-engine.aegismesh:8000/analyze"
        - name: DATADOG_APIKEY
          valueFrom:
            secretKeyRef:
              name: security-secrets
              key: datadog-api-key
              optional: true
        - name: DATADOG_HOST
          value: "https://api.us5.datadoghq.com"
---
apiVersion: v1
kind: Service
metadata:
  name: falcosidekick
  namespace: aegismesh
spec:
  selector:
    app: falcosidekick
  ports:
  - protocol: TCP
    port: 2801
    targetPort: 2801
