apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../manifests
  - ../../networkpolicies
  - sealedsecret-aegismesh.yaml

patches:
  - path: patch-backend-image.yaml
  - path: patch-frontend-image.yaml
  - path: patch-resources.yaml

images:
  - name: 654654364687.dkr.ecr.us-east-1.amazonaws.com/aegismesh-backend
    newName: aegismesh-backend
    newTag: local-v2
  - name: 654654364687.dkr.ecr.us-east-1.amazonaws.com/aegismesh-frontend
    newName: aegismesh-frontend
    newTag: local
  - name: aegismesh-security-engine
    newName: aegismesh-security-engine
    newTag: latest
