apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../manifests
  - sealedsecret-aegismesh.yaml

patches:
  - path: patch-backend-image.yaml
  - path: patch-frontend-image.yaml
  - path: patch-resources.yaml
