apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../manifests

patchesStrategicMerge:
  - patch-backend-image.yaml
  - patch-frontend-image.yaml
  - patch-resources.yaml
