apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: aegismesh
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:17-alpine
          imagePullPolicy: IfNotPresent
        - name: prisma-migrate
          image: 654654364687.dkr.ecr.us-east-1.amazonaws.com/aegismesh-backend:a5e3691acdd7ebc64baa4f445eede5a7b8fcc78d
          imagePullPolicy: IfNotPresent
      containers:
        - name: backend
          image: 654654364687.dkr.ecr.us-east-1.amazonaws.com/aegismesh-backend:a5e3691acdd7ebc64baa4f445eede5a7b8fcc78d
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
