apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: aegismesh
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: 654654364687.dkr.ecr.us-east-1.amazonaws.com/aegismesh-frontend:08b144459bbd6fb96b6b468b497d1c1d484b3c32
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
