apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: aegismesh
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ecr-regcred
      containers:
        - name: frontend
          image: REPLACE_FRONTEND_IMAGE
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
