apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aegismesh-app-monitor
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
    - aegismesh
  endpoints:
  - port: http
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: security-engine-monitor
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: security-engine
  namespaceSelector:
    matchNames:
    - aegismesh
  endpoints:
  - port: metrics
    path: /metrics/
