apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegismesh

resources:
  - manifests/namespace.yaml
  - manifests/secret.yaml
  - manifests/configmap.yaml
  - manifests/postgres.yaml
  - manifests/backend.yaml
  - manifests/frontend.yaml
