apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegismesh

resources:
  - manifests/namespace.yaml
  - manifests/configmap.yaml
  - manifests/postgres.yaml
  - manifests/backend.yaml
  - manifests/frontend.yaml
  - manifests/security-engine.yaml
  - manifests/redis.yaml
  - hpa/backend-hpa.yaml
  - networkpolicies/default-deny.yaml
  - networkpolicies/allow-backend-to-postgres.yaml
  - networkpolicies/allow-dns.yaml
  - networkpolicies/security-engine-policies.yaml
  - networkpolicies/allow-crowdsec-egress.yaml
  - networkpolicies/allow-falcosidekick-egress.yaml
  - networkpolicies/allow-postgres-from-monitoring.yaml
  - manifests/datadog-agent.yaml
  - networkpolicies/allow-datadog-agent-traffic.yaml

images:
  - name: 654654364687.dkr.ecr.us-east-1.amazonaws.com/aegismesh-backend
    newName: aegismesh-backend
    newTag: local-v2
  - name: 654654364687.dkr.ecr.us-east-1.amazonaws.com/aegismesh-frontend
    newName: aegismesh-frontend
    newTag: local
  - name: aegismesh-security-engine
    newName: aegismesh-security-engine
    newTag: latest


