apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny.yaml
  - allow-backend-to-postgres.yaml
  - allow-dns.yaml
  - security-engine-policies.yaml
  - allow-crowdsec-egress.yaml
  - allow-falcosidekick-egress.yaml
  - allow-postgres-from-monitoring.yaml
  - allow-datadog-agent-traffic.yaml
