apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-operator
  template:
    metadata:
      labels:
        app: trivy-operator
    spec:
      serviceAccountName: trivy-operator
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: trivy-operator
        image: ghcr.io/aquasecurity/trivy-operator:0.22.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_SCAN_ALL_NAMESPACES
          value: "true"
        - name: OPERATOR_RESOURCES_CONFIG_MAP_NAME
          value: "trivy-operator"
        - name: OPERATOR_VULNERABILITY_REPORTS_SCANNER
          value: "Trivy"
        - name: OPERATOR_CONFIG_AUDIT_REPORTS_SCANNER
          value: "Trivy"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
