apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - backend-hpa.yaml
  - redis.yaml
  - security-engine.yaml
  - security-engine-training-cronjob.yaml
  - datadog-agent.yaml
  - crowdsec/crowdsec.yaml
  - falcosidekick/falcosidekick.yaml
  - ecr-registry-refresher.yaml
