apiVersion: v1
kind: Secret
metadata:
  name: aegismesh-secrets
  namespace: aegismesh
type: Opaque
stringData:
  DB_NAME: " "
  DB_USER: " "
  DB_PASSWORD: " "
  DATABASE_URL: " "
  JWT_SECRET: " "
  JWT_ACCESS_SECRET: " "
  JWT_REFRESH_SECRET: " "
  JWT_REAUTH_SECRET: " "
  REFRESH_TOKEN_SECRET: " "
  SMTP_HOST: " "
  SMTP_PORT: " "
  SMTP_USER: " "
  SMTP_PASS: " "
  SMTP_FROM: " "
  GOOGLE_CLIENT_ID: " "
  GOOGLE_CLIENT_SECRET: " "
  GOOGLE_CALLBACK_URL: " "
  GITHUB_CLIENT_ID: " "
  GITHUB_CLIENT_SECRET: " "
  GITHUB_CALLBACK_URL: " "
