apiVersion: v1
kind: Service
metadata:
  name: security-engine
  namespace: aegismesh
spec:
  selector:
    app: security-engine
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-engine
  namespace: aegismesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-engine
  template:
    metadata:
      labels:
        app: security-engine
    spec:
      containers:
      - name: security-engine
        image: aegismesh-security-engine:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: aegismesh-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: aegismesh-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aegismesh-secrets
              key: DB_PASSWORD
        - name: DATABASE_URL
          value: postgresql://$(DB_USER):$(DB_PASSWORD)@postgres.aegismesh.svc.cluster.local:5432/$(DB_NAME)
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow.monitoring:5000"
